# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import object_coordinates_pb2 as object__coordinates__pb2


class coordinatesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getCoordinates = channel.unary_unary(
                '/RpcDemo.coordinatesService/getCoordinates',
                request_serializer=object__coordinates__pb2.Empty.SerializeToString,
                response_deserializer=object__coordinates__pb2.PointStamped.FromString,
                )


class coordinatesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getCoordinates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_coordinatesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getCoordinates': grpc.unary_unary_rpc_method_handler(
                    servicer.getCoordinates,
                    request_deserializer=object__coordinates__pb2.Empty.FromString,
                    response_serializer=object__coordinates__pb2.PointStamped.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RpcDemo.coordinatesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class coordinatesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getCoordinates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RpcDemo.coordinatesService/getCoordinates',
            object__coordinates__pb2.Empty.SerializeToString,
            object__coordinates__pb2.PointStamped.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
